/* eslint-disable */

export default  {
  // 连接socket
  CONNECT: 'connect',
  // 取消连接
  DISCONNECT: 'disconnect',
  // 重新连接后
  RECONNECT: 'reconnect',
  // 重新连接开始
  RECONNECT_ATTEMPT: 'reconnect_attempt',
  // 房间关闭
  CLOSE_ROOM: 'closeRoom',
  // 房间打开
  OPEN_ROOM: 'openRoom',
  // 系统公告
  SYSTEM_ANNOUNCEMENT: 'gonggao',
  // 用户发言
  SPEAK: 'speak',
  // 发言错误
  SPEAK_ERROR: 'speakError',
  // 发言审核
  SPEAK_CENSOR: 'speak_censor',
  // 奖励信息
  REWARD: 'reward',
  // 提问
  QUESTION: 'question',
  // 关闭提问
  CLOSE_QUESTION: 'closeQuestion',
  // 回答
  ANSWER: 'answer',
  // 自定义信息
  CUSTOMER_MESSAGE: 'customerMessage',
  // 后台出错
  SERVER_ERROR: 'serverError',
  // 用户被踢
  KICK_USER: 'kickUser',
  // 清楚聊天记录
  REMOVE_HISTORY: 'removeHistory',
  // 清除某条聊天记录
  REMOVE_CONTENT: 'removeContent',
  // 关闭弹幕
  CLOSE_DANMU: 'closeDanmu',
  // socket错误
  ERROR: 'error',
  // 获取历史聊天信息
  HISTORY_MESSAGE: 'historyMessage',
  // 发送消息成功
  SEND_MESSAGE: 'sendMessage',
  // 禁止发言
  PROHIBIT_TO_SPEAK: 'prohibitToSpeak',
  // 登录
  LOGIN: 'login',
  // 退出登录
  LOGOUT: 'loginOut',
  // 用户更新
  UPDATEUSER: 'updateUser',
  // 上课
  CLASSSTART: 'onClassStart',
  // 下课
  CLASSEND: 'onClassEnd',
  // 当前上下课状态
  SLICEID: 'onSliceID',
  // 云课堂上课
  SLICESTART: 'onSliceStart',
  // 教师控制
  CLASSCONTROL: 'onClassControl',
  // 全体上下麦
  MUTEALLVIDEO: 'muteAllVideo',
  // 全体静音和恢复
  MUTEALLAUDIO: 'muteAllAudio',
  // 静音某一个学员
  MUTEUSERAUDIO: 'muteUserAudio',
  // 下麦某一个学员
  MUTEUSERVIDEO: 'muteUserVideo',

  SLICECONTROL: 'onSliceControl',
  // 画笔
  SLICEDRAW: 'onSliceDraw',

  SLICEDOPEN: 'onSliceOpen',

  // 学生提问
  S_QUESTION: 'S_QUESTION',
  // 教师或助教或管理员回答问题
  T_ANSWER: 'T_ANSWER',
  // 更新提问历史记录
  UPDATE_QUESTION_HISTROY: 'UPDATE_QUESTION_HISTROY',
  // 收到普通公告
  BULLETIN: 'bulletin',
  // 移除普通公告
  REMOVE_BULLETIN: 'removeBulletin',
  // 送花
  FLOWERS: 'FLOWERS',
  // 红包
  REDPAPER: 'redpaper',
  // 开始签到
  SIGN_IN: 'SIGN_IN',
  // 停止签到
  STOP_SIGN_IN: 'STOP_SIGN_IN',
  // 观看页点击进行签到
  TO_SIGN_IN: 'TO_SIGN_IN',
  // 点赞
  LIKES: 'LIKES',
  //连麦
  MICROPHONE: 'OPEN_MICROPHONE',
  // 允许连麦
  ALLOW_MICROPHONE: 'ALLOW_MICROPHONE',
  //  连麦成功
  SUCCESS_MICROPHONE: 'SUCCESS_MICROPHONE',
  //  加入频道失败
  JOIN_CHANNEL_FAIL: 'JOIN_CHANNEL_FAIL',
  // 设置昵称
  SET_NICK: 'SET_NICK',
  // 已在线教师信息
  ONLINE_TEACHERINFO: 'O_TEACHER_INFO',
  // 超时未连接聊天室
  OVERTIMECONNECT: 'overtimeConnect',
  // 修改管理员信息
  SET_MANAGER_INFO: 'SET_MANAGER_INFO',
  // 答题卡: 获取问题内容
  GET_TEST_QUESTION_CONTENT: 'GET_TEST_QUESTION_CONTENT',
  // 答题卡: 获取答题结果
  GET_TEST_QUESTION_RESULT: 'GET_TEST_QUESTION_RESULT',
  // 答题卡：停止答题
  STOP_TEST_QUESTION: 'STOP_TEST_QUESTION',
  // 禁止进入聊天室
  BAN_USER_ROOM: 'ban_user_room',

  // 系统消息
  SYSTEM_MESSAGE: 'SYSTEM_MESSAGE',
  // 图片
  CHAT_IMG: 'CHAT_IMG',
  // 被踢出
  LOGIN_KICK: 'LOGIN_KICK'
};
